### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by tonioo** [tonioo/sievelib#26]
Add support for Python >= 3.3

**Comment by frafra** [comment]
```
>>> import sievelib.factory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/sievelib/factory.py", line 309
    print "Dumping filters set %s\n" % self.name
                                   ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by tonioo** [comment]
The python3 compat has not been released yet, it will be with 0.9. If you want to try it, use the master branch.

**Comment by fladi** [comment]
Any estimates on when 0.9 will be released?

**Comment by tonioo** [comment]
There are still a few things to fix before the release. Maybe this month...
